AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Buffoonery SSL certificate 

Parameters: 
  CertDomainName: 
    Type: String 
    Description: Domain name for the certificate 
  HostedZoneId: 
    Type: String 
    Description: id of the hosted zone for the cert domain 
  StageName:
    Type: String
    Description: the development stage
Resources:

  GeneratedCert: # If a Certificate ARN is not passed in the parameters, then a new cert is created and will required validation during the deploy
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref CertDomainName
      DomainValidationOptions: 
        - DomainName: !Ref CertDomainName 
          HostedZoneId: !Ref HostedZoneId 
      SubjectAlternativeNames: 
        - !Sub '*.${CertDomainName}'
      ValidationMethod: DNS

Outputs: 
  CertificateArn: 
    Description: "Certificate Arn "
    Value: !Ref GeneratedCert