AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack to deploy Buffoonery's Architecture

Parameters:
  StageName:
    Type: String
    Description: the development stage
    AllowedValues:
      - dev
      - qa
      - prod
  MyHostedZone:
    Type: String
    Description: Hosted Zone Id
    Default: Z05631881PTE1Z2JRRP6J
  MyDomainName:
    Type: String
    Description: domain name
    Default: buffoonery.io
  ApiSubdomain:
    Type: String
    Description: Api Domain
    AllowedValues:
      - api

Resources:
  LambdaWebsocket:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda-websocket/template.yaml
      Parameters:
        StageName: !Ref StageName
        MyDomainName: !Ref MyDomainName
        ApiSubdomain: !Ref ApiSubdomain
        HostedZoneId: !Ref MyHostedZone
