AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Websocket API and components

Parameters:
  StageName:
    Type: String
    Description: the development stage
    AllowedValues:
      - dev
      - qa
      - prod
  CertArn:
    Type: String
    Description: Certificate Manager Arn for the ssl cert if one has already been created
    Default: none
  MyDomainName:
    Type: String
    Description: Api Domain
    Default: buffoonery.io
  ApiSubdomain:
    Type: String
    Description: Api Domain
    Default: api
    AllowedValues:
      - api
  HostedZoneId:
    Type: String
    Description: Route53 Hosted zone ID if one has already been created
    Default: Z05631881PTE1Z2JRRP6J

Conditions:
  CreateCert: !Equals [!Ref CertArn, 'none']

Globals:
  Function:
    Timeout: 5
    Handler: index.handler
    Runtime: nodejs12.x

Resources:
  GeneratedCert: # If a Certificate ARN is not passed in the parameters, then a new cert is created and will required validation during the deploy
    Type: AWS::CertificateManager::Certificate
    Condition: CreateCert
    Properties:
      DomainName: !Ref MyDomainName
      DomainValidationOptions:
        - DomainName: !Ref MyDomainName
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
        - !Sub '*.${MyDomainName}'
      ValidationMethod: DNS

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
      Domain:
        DomainName: !Sub '${StageName}-${ApiSubdomain}.${MyDomainName}' # ie: dev-api.buffoonery.io
        CertificateArn: !If [CreateCert, !Ref GeneratedCert, !Ref CertArn]
        EndpointConfiguration: EDGE
        BasePath: /
        Route53:
          HostedZoneId: !Ref HostedZoneId
      Cors:
        AllowMethods: "'GET, POST, PUT, OPTIONS, DELETE'"
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"

  GameroomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: roomcode
          AttributeType: S
      KeySchema:
        - AttributeName: roomcode
          KeyType: HASH

  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: category
          KeyType: HASH
  WebSocketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'websocket-gamerooms-${StageName}'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg

  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg

  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations

  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendInteg

  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - SendRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref WebSocketAPI

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref StageName
      Description: !Sub '${StageName} Stage'
      DeploymentId: !Ref Deployment
      ApiId: !Ref WebSocketAPI

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Handler: index.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref GameroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameroomsTable
        - SNSCrudPolicy:
            TopicName: ClientConnected

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: index.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref GameroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameroomsTable
        - SNSCrudPolicy:
            TopicName: ClientDisconnected

  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sendmessage/
      Handler: index.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref GameroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameroomsTable
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*'
  SendMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SendMessageFunction
      Principal: apigateway.amazonaws.com

  ClientConnectedGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: client-connected-get
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to get connected clients
      Environment:
        Variables:
          TableName: !Ref GameroomsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GameroomsTable
      Events:
        BuffooneryRestApiGet:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /GetGameroomState/{roomcode}
            Method: GET
            Auth:
              ApiKeyRequired: true

  PromptCategoriesGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: prompt-categories-get
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to get prompt categories and associated prompts
      Environment:
        Variables:
          TableName: !Ref CategoriesTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiGet:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /GetPromptCategories
            Method: GET
            Auth:
              ApiKeyRequired: true

  DistributePromptsToPlayersPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: distribute-prompts-to-players-put
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to distribute random prompts to players in a specific gameroom
      Environment:
        Variables:
          CategoriesTableName: !Ref CategoriesTable
          GameroomsTableName: !Ref GameroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameroomsTable
        - DynamoDBReadPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiPut:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /DistributePromptsToPlayers/{roomcode}
            Method: PUT
            Auth:
              ApiKeyRequired: true

  CategoryPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: category-put
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to add/update a prompt category to the database.
      Environment:
        Variables:
          TableName: !Ref CategoriesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiPut:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /SaveCategory
            Method: PUT
            Auth:
              ApiKeyRequired: true

  CategoryDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: category-delete
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to delete a category and its prompts from the Categories table.
      Environment:
        Variables:
          TableName: !Ref CategoriesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiPut:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /DeleteCategory
            Method: DELETE
            Auth:
              ApiKeyRequired: true

  PromptPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: prompt-put
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to add/update a prompt (associated to a category entry) in the Categories table.
      Environment:
        Variables:
          TableName: !Ref CategoriesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiPut:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /SavePrompt
            Method: PUT
            Auth:
              ApiKeyRequired: true

  PromptDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: prompt-delete
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 256
      Description: A function to delete a prompt from its parent category entry in the Categories table.
      Environment:
        Variables:
          TableName: !Ref CategoriesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
      Events:
        BuffooneryRestApiPut:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /DeletePrompt
            Method: DELETE
            Auth:
              ApiKeyRequired: true

  GetAPIKeyLambda:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        var response = require('cfn-response');
        var AWS = require('aws-sdk');

        exports.handler = function(event, context) {
          var apiKeyID = event.ResourceProperties.ApiKeyID;
          var apigateway = new AWS.APIGateway();
          var params = {
            apiKey: apiKeyID,
            includeValue: true
          };

          var responseData = {};

          apigateway.getApiKey(params, function(err, ApiKeyData) {
            if (err) {
              console.log(err, err.stack); // an error occurred
              responseData = { "myapikey" : "error reading ApiKey" };
              response.send(event, context, response.SUCCESS, responseData);
            } else {
              console.log(ApiKeyData.value);      // successful response
              responseData = { "myapikey" : ApiKeyData.value };
              response.send(event, context, response.SUCCESS, responseData);
            }
          });
        };
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'apigateway:GET'
              Resource: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}::/apikeys/*'

  GetApiKeyValue:
    Type: Custom::LambdaGetApiKeyValue
    Properties:
      ServiceToken: !GetAtt GetAPIKeyLambda.Arn
      ApiKeyID: !Ref RestApiGatewayApiKey

Outputs:
  ApiKey:
    Description: The api key from API Gateway
    Value: !GetAtt GetApiKeyValue.myapikey
    Export:
      Name: !Sub '${AWS::StackName}-ApiKey'
  ApiEndpoint:
    Description: 'REST API endpoint URL'
    Value: !Sub 'https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/'

  GameroomsTableArn:
    Description: 'Gamerooms table ARN'
    Value: !GetAtt GameroomsTable.Arn

  GameroomsTableName:
    Description: 'Gamerooms table ARN'
    Value: !Ref GameroomsTable

  OnConnectFunctionArn:
    Description: 'OnConnect function ARN'
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: 'OnDisconnect function ARN'
    Value: !GetAtt OnDisconnectFunction.Arn

  SendMessageFunctionArn:
    Description: 'SendMessage function ARN'
    Value: !GetAtt SendMessageFunction.Arn

  WSAPIDomain:
    Description: 'The WebSocket api domain'
    Value:
      !Join [
        '',
        [
          !Ref WebSocketAPI,
          '.execute-api.',
          !Ref 'AWS::Region',
          '.amazonaws.com'
        ]
      ]

  WebSocketURI:
    Description: 'The WSS Protocol URI to connect to'
    Value:
      !Join [
        '',
        [
          'wss://',
          !Ref WebSocketAPI,
          '.execute-api.',
          !Ref 'AWS::Region',
          '.amazonaws.com/',
          !Ref 'Stage'
        ]
      ]
