AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Buffoonery Route53 stack

Parameters:
  StageName:
    Type: String
    Description: the development stage
  ApiDomainName:
    Type: String
    Description: the hosted zone to create
  HostedZoneId: 
    Type: String 
    Description: Route53 Hosted zone ID if one has already been created 
  ApiCertificateArn: 
    Type: String 
    Description: API Certificate arn
  ApiSubdomain:
    Type: String
    Description: Api Domain
    AllowedValues:
      - api
Resources:
  GeneratedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ApiDomainName

  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref ApiCertificateArn
      DomainName: !Ref ApiDomainName

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub '${StageName}.${ApiSubdomain}.${ApiDomainName}'
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref StageName

  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref ApiDomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt APIDomainName.DistributionDomainName
          HostedZoneId: !Ref HostedZoneId # static ID for CloudFront aliases
Outputs:
  HostedZoneId:
    Description: the id of the new hosted zone
    Value: !Ref GeneratedZone

